export const beneficiaries = [
  {
    id: 1,
    name: 'Asha Verma',
    uid: 'UID-2489-1177',
    schemes: ['Central Pension', 'State Health'],
    state: 'Maharashtra',
    status: 'Verified',
  },
  {
    id: 2,
    name: 'Rahul Nair',
    uid: 'UID-7432-9133',
    schemes: ['Central Pension'],
    state: 'Kerala',
    status: 'Pending',
  },
  {
    id: 3,
    name: 'Meera Iyer',
    uid: 'UID-5561-4421',
    schemes: ['State Pension', 'Central Pension'],
    state: 'Tamil Nadu',
    status: 'Duplicate',
  },
  {
    id: 4,
    name: 'Kabir Singh',
    uid: 'UID-1312-7740',
    schemes: ['Defense Pension'],
    state: 'Punjab',
    status: 'Verified',
  },
  {
    id: 5,
    name: 'Pooja Das',
    uid: 'UID-9092-0082',
    schemes: ['State Pension'],
    state: 'West Bengal',
    status: 'Under Review',
  },
  {
    id: 6,
    name: 'Arun Joshi',
    uid: 'UID-3021-4408',
    schemes: ['Central Pension', 'State Pension'],
    state: 'Gujarat',
    status: 'Duplicate',
  },
  {
    id: 7,
    name: 'Farah Khan',
    uid: 'UID-6155-3378',
    schemes: ['Central Pension'],
    state: 'Delhi',
    status: 'Verified',
  },
  {
    id: 8,
    name: 'Vikram Rao',
    uid: 'UID-0018-2239',
    schemes: ['State Pension'],
    state: 'Karnataka',
    status: 'Pending',
  },
];
